### ISSUE TITLE
NPM global package installs don't work unless plugin is installed as "nodejs"

### ISSUE THREAD

**Issue by bsedat** [asdf-vm/asdf-nodejs#20] opened 2016-08-04 18:11 UTC
The npm package postinstall hook tries to call `npm shim nodejs`, but that command errors out if the plugin is installed by another name (like "node"). Is there a good way to tell asdf that I've customized the name of the plugin? Or should I just edit my postinstall hook manually for now?

**Comment by ndarilek** [comment] 2016-09-23 15:23
This just bit me as well. Seems like the postinstall script could guess the plugin name by looking at the installation directory. Unfortunately I'm not a competent enough Bash scripter to add that in. I changed my plugin's name for now, but it wasn't quite as seamless of an experience as I might have hoped. Also, if ASDF lets you install plugins under any name, perhaps it could/does inject that name into the shell script's environment so it can be used in commands, as is done here.

Either way, only a minor wrinkle. Nice project.

**Comment by SoreGums** [comment] 2016-09-28 11:24
oh man! - glad this is here, has held me up for the better part on hour tracking down what the issue is.
basically make sure added node as "nodejs" and it just works

asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git

:)

**Comment by mikebaldry** [comment] 2017-01-25 16:27
Took me half an hour of head scratching to find out why it was failing. Thanks. Be nice to get this updated! Why do you even need to name plugins? Can't they just pick up the name from the plugin...

**Comment by faraazahmad** [comment] 2018-02-07 14:06
@SoreGums i did the following

```
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs 9.5.0
```
But the problem still remains. for example, when i globally install `browser-sync` i get this
```
npm WARN lifecycle The node binary used for scripts is /home/faraaz/.asdf/shims/node but npm is using /home/faraaz/.asdf/installs/nodejs/9.5.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

```

**Comment by bsedat** [comment] 2018-02-07 22:01
@faraazahmad I think your error is a separate bug - it might be better off in a new Github issue.

**Comment by faraazahmad** [comment] 2018-02-08 06:00
So i just ran `asdf reshim nodejs` and global packages now work. What could be the reason? Should i open an issue for it?

**Comment by axelson** [comment] 2018-02-17 21:42
Are you supposed to run `asdf reshim nodejs` after installing a global package?

**Comment by faraazahmad** [comment] 2018-02-18 07:56
@axelson I just ran it once and everything now works as I expect it to, I never had to re run that since.

**Comment by axelson** [comment] 2018-02-18 18:17
Okay, thanks! Hopefully that'll work for me too.

**Comment by davelnewton** [comment] 2018-06-01 20:43
Re-shimming does *not* work for me, under OS X.

I installed `create-react-native-app` via:

```
npm i -g create-react-native-app
```

in a `.tool-versions`ed directory.

* `which node` and `which npm` show I'm running the asdf bins.
* `npm list -g` shows it installed in the proper asdf lib directory.
* `npm bin` shows only the local `node_modules/.bin` directory.
* The binary for `create-react-native-app` *is* in the asdf installs directory.

Hrm. I'm leaving the above for completeness--the only thing that isn't working is zsh executable auto-complete: if I type the full command name it runs--but not sure how.

**Comment by Stratus3D** [comment] 2020-01-14 14:44
@bsedat is this still an issue?

**Comment by Stratus3D** [comment] 2020-01-14 14:56
@bsedat can you see if this PR fixes your issue? https://github.com/asdf-vm/asdf-nodejs/pull/150

**Comment by Stratus3D** [comment] 2020-01-15 12:39
Closing since I think #150 fixed this.

**Closed by Stratus3D** 2020-01-15 12:39 UTC
Labels: help wanted, needs investigation
