### ISSUE TITLE
WSL 2 - Ubuntu 18.04

### ISSUE THREAD

**Issue by haroldofurtado** [asdf-vm/asdf-nodejs#140] opened 2019-09-06 06:31 UTC
When I try to use the command:

bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

I just receive gpg: keyserver receive failed: Server indicated a failure

**Comment by aanarchy** [comment] 2019-11-11 11:46
I have the same issue. I want to use asdf, but these issues are discouraging me

**Comment by aanarchy** [comment] 2019-11-11 11:49
Fixed the issue. Turns out you have to let the entire script run because it runs each key to each server.

**Comment by Stratus3D** [comment] 2019-12-23 14:41
Yes, the script will try multiple servers. It is only a problem when all the servers fail, which I have not observed. Closing this issue as it is not a bug. If you want to improve the script feel free to open a PR.

**Closed by Stratus3D** 2019-12-23 14:41 UTC

**Comment by vvavrychuk** [comment] 2021-01-22 04:13
@Stratus3D do you have some idea how to improve script?

Even so it succeeds at the end. Execution takes 13 seconds and it is very tempting to suspect that script hang and stop it.

Complete log
```
$ time bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/impor
t-release-team-keyring'
gpg: keyserver receive failed: Server indicated a failure
gpg: /home/vasyl/.gnupg/trustdb.gpg: trustdb created
gpg: key D7062848A1AB005C: public key "Beth Griggs <bgriggs@redhat.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key 7434390BDBE9B9C5: public key "Colin Ihrig <cjihrig@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key D3A89613643B6201: public key "Danielle Adams <adamzdanielle@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key C97EC7A07EDE3FC1: public key "keybase.io/jasnell <jasnell@keybase.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key 770F7A9A5AE15600: public key "Michaël Zasso (Targos) <targos@protonmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key E73BC641CC11F4C8: public key "Myles Borins <myles.borins@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key C43CEC45C17AB93C: public key "Richard Lau <rlau@redhat.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key C273792F7D83545D: public key "Rod Vagg <rod@vagg.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key F07496B3EB3C1762: public key "Ruben Bridgewater <ruben@bridgewater.de>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key 97B01419BD92F80A: public key "Ruy Adorno <ruyadorno@hotmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: key F13993A75599653C: public key "Shelley Vohr (security is major key) <shelley.vohr@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1

real    0m13.355s
user    0m0.128s
sys     0m0.040s
```
