### ISSUE TITLE
Fail to install Atom Editor plugin

### ISSUE THREAD

**Issue by AlexWayfer** [asdf-vm/asdf-nodejs#164] opened 2020-05-23 21:59 UTC
Package: `platformio-ide-terminal 2.10.0`

```
npm WARN lifecycle The node binary used for scripts is /home/alex/.asdf/shims/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
unknown command: node. Perhaps you have to reshim?
unknown command: node. Perhaps you have to reshim?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.atom/.apm/_logs/2020-05-23T21_58_08_397Z-debug.log
```

**Comment by augustobmoura** [comment] 2023-05-20 17:25
As we reached Atom's EOL, I will be closing this issue as part of greenkeeping the issues. The problem is more related to how asdf works, by creating shims as opposed to other version managers that setup the PATH environment variable.

**Closed by augustobmoura** 2023-05-20 17:25 UTC

**Comment by AlexWayfer** [comment] 2023-05-20 17:45
> As we reached Atom's EOL

There is alive Atom's fork [Pulsar](https://pulsar-edit.dev/).

Are you sure about closing this issue? Especially "as completed" instead of "as not planned".

**Comment by augustobmoura** [comment] 2023-05-20 17:55
I was not aware of Pulsar. Is this still an issue in there? It looks like [`ppm` its packaging](https://github.com/pulsar-edit/ppm/blob/feea558a565b8c12ee2d1d2afceb95602e24cf5d/bin/apm#L42) its own node version and I couldn't reproduce the issue

**Comment by augustobmoura** [comment] 2023-05-20 18:02
Might be an issue with `platformio-ide-terminal`, but I couldn't build it from `ppm` in any case. Do you have another reproduction case? Feel free to open a new issue for the case of Pulsar, I believe this one should be only related to Atom, which stalled in contribuitions

**Comment by AlexWayfer** [comment] 2023-05-20 18:10
> Might be an issue with `platformio-ide-terminal`, but I couldn't build it from `ppm` in any case. Do you have another reproduction case? Feel free to open a new issue for the case of Pulsar, I believe this one should be only related to Atom, which stalled in contribuitions

OK, I got you, thanks. I'll if I'd face the issue, but for now I'm away from `asdf`. Just for clarification and history.
