### ISSUE TITLE
postinstall breaks npm upgrade

### ISSUE THREAD

**Issue by jonatan-ivanov** [asdf-vm/asdf-nodejs#226] opened 2021-04-10 20:42 UTC
The [`postinstall`](https://github.com/asdf-vm/asdf-nodejs/blob/d56626aadd4b79571a9556bf6f404326e0e17152/npm-hooks/postinstall) script breaks `npm upgrade -g`, here is the related line of the output of the cmd:
`npm ERR! Invalid package name ".hooks": name cannot start with a period`

Indeed, there is a `.hooks` folder: `~/.asdf/installs/nodejs/15.14.0/.npm/lib/node_modules/.hooks/postinstall` (re)moving it fixes the issue.

### Full Output

```
 ❯ npm upgrade -g                                                                                                                          
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name ".hooks": name cannot start with a period

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2021-04-10T20_36_56_004Z-debug.log
```

**Comment by augustobmoura** [comment] 2021-04-10 22:52
This is a [regression introduced in npm@7](https://github.com/npm/cli/issues/2692), the workaround for now is to remove the `.hooks` folder and running `asdf reshim nodejs` manually after every global install. In the meantime I will research a way of asdf-nodejs not rely in .hooks

**Comment by augustobmoura** [comment] 2021-07-19 22:38
This issue should be fixed in master because I actively removed the lines of code that were creating the `.hooks` directory. If the problem persists, please comment below so that I open the thread again

**Closed** 2021-07-19 22:38 UTC
