### ISSUE TITLE
gpg keyserver receive failed

### ISSUE THREAD

**Issue by benfalk** [asdf-vm/asdf-nodejs#259] opened 2021-09-22 19:35 UTC
Hey 👋 

Just recently installed `asdf` along with the default nodejs plugin and when I try to install any version of nodejs I get the following output:

```
gpg: keyserver receive failed: Network is unreachable
gpg: keyserver receive failed: No keyserver available
```

I get this message about ~40 times before it fails declaring it cannot install whichever version I try.

I installed asdf via `homebrew` and am on the the latest version of Big Sir.

```bash
asdf --version
# v0.8.1
```

```bash
asdf plugin update nodejs                                                                                                                                      
Updating nodejs to master
Already on 'master'
Your branch is up to date with 'origin/master'.
```

**Comment by augustobmoura** [comment] 2021-10-03 00:28
Duplicate of #241

**Closed by augustobmoura** 2021-10-03 00:28 UTC
