### ISSUE TITLE
How to update npm?

### ISSUE THREAD

**Issue by ihackalot** [asdf-vm/asdf-nodejs#57] opened 2017-10-09 16:09 UTC
I installed node 8.6.0 which comes with npm 5.3.0. I wanted to update npm to 5.4.2 but neither `npm i -g npm@latest` nor `npm up -g npm` work. Instead, a new npm is installed inside `~/.asdf/installs/nodejs/8.6.0/.npm/lib/node_modules` because of the environment config setting `prefix = "~/.asdf/installs/nodejs/8.6.0/.npm"`. How am I supposed to perform the update?

```
$ npm -v
5.3.0
$ npm i -g npm@latest
+ npm@5.4.2
$ asdf reshim nodejs
$ npm -v
5.3.0
```
😔

**Comment by mareksuscak** [comment] 2017-10-23 10:41
duplicate of #56

**Comment by psantos10** [comment] 2018-04-27 17:36
@ihackalot unfortunately this tip does not work:

```console
$ npm -v
5.8.0
$ cd ~/.asdf/installs/nodejs/9.11.1/lib && npm update npm
$ asdf reshim nodejs
$ npm -v
5.8.8
$ which node
/Users/psantos/.asdf/shims/node
$ which npm
/Users/psantos/.asdf/shims/npm
```

Same issue 😞

**Comment by ihackalot** [comment] 2018-04-27 18:06
Which asdf version are you running? Try to `asdf update` and `asdf plugin-update nodejs. It works for me running asdf v0.4.3.

**Comment by joemsak** [comment] 2018-05-24 13:28
Coming from https://github.com/asdf-vm/asdf-nodejs/issues/56#issuecomment-391583768 it works for me thanks

**Comment by sardaukar** [comment] 2018-08-31 15:28
Wasn't working for me either, did an update of asdf and the nodejs plugin and it now works fine in a new shell.

**Comment by Stratus3D** [comment] 2018-10-02 15:50
I believe this has been address under #56 and the related issues.

**Closed by Stratus3D** 2018-10-02 15:50 UTC

**Comment by szymon-jez** [comment] 2020-08-05 08:15
_(I know that this is a very dated issue but somehow I was bitten by this recently in a dated environment and thought to share my experience here)_

---

This is what helped me out:

```bash
npm install -g npm@6.1.0
asdf update
asdf plugin-update nodejs
asdf reshim
npm --version
# => 6.1.0
```

---

First I had issues like @MOPineyro here https://github.com/asdf-vm/asdf-nodejs/issues/57#issuecomment-391776032 but `asdf plugin-update nodejs` seemed to do the trick.

**Comment by fxsalazar** [comment] 2021-11-25 13:21
Me too: (I know that this is a very dated issue but somehow I was bitten by this recently in a dated environment and thought to share my experience here)

The only thing that helped me was https://github.com/asdf-vm/asdf-nodejs/issues/57#issuecomment-391582535

Is this something that was _fixed_?

**Comment by augustobmoura** [comment] 2025-06-05 23:25
Probably not the same issue, we don't use `.npm` prefixes anymore. Could you give more information on what problems are you having?

Also, could you please run `asdf info` and send me the output?

**Comment by BinaryPaean** [comment] 2025-06-05 23:26
> Probably not the same issue, we don't use `.npm` prefixes anymore. Could you give more information on what problems are you having?
> 
> Also, could you please run `asdf info` and send me the output?

Wow you're fast like a ninja. Just updated my comment with more info.

Asdf info:
```
asdf info
OS:
Linux DESKTOP-U759FAO 6.6.87.1-microsoft-standard-WSL2 #1 SMP PREEMPT_DYNAMIC Mon Apr 21 17:08:54 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
zsh 5.9 (x86_64-ubuntu-linux-gnu)

BASH VERSION:
5.2.37(1)-release

ASDF VERSION:
0.17.0 (revision unknown)

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/home/aaron/.asdf
ASDF_CONFIG_FILE=/home/aaron/.asdfrc

ASDF INSTALLED PLUGINS:
bun       https://github.com/cometkim/asdf-bun.git
          019058c3a9f408a06bab63a4a3782c555a8dde3c
elixir    https://github.com/asdf-vm/asdf-elixir.git
          89098d5c31fd3a240a25b1dacf881a6eeed426c4
erlang    https://github.com/asdf-vm/asdf-erlang.git
          5f27baa62864bb433be9c7f2f7d69b475f534376
golang    https://github.com/asdf-community/asdf-golang.git
          50c8f58237da34223d31ac9e62e5d5f8dcc13f5f
lua       https://github.com/Stratus3D/asdf-lua.git
          1ebd84967ed6b7aefeb4300cfcb211f414be0226
nodejs    https://github.com/asdf-vm/asdf-nodejs.git
          fd2c7f94c4c71416047cacf2af6e4fa819b364b7
```

**Comment by hcientist** [comment] 2025-06-11 17:45
I think I am having the same issue. should this issue be reopened?

**Comment by BinaryPaean** [comment] 2025-06-11 20:58
More info that seems relevant but I don't fully understand:

```
> npx --version
11.4.1

> npm --version
8.5.5

> asdf which npm
/home/aaron/.asdf/plugins/nodejs/shims/npm

> asdf which npx
/home/aaron/.asdf/installs/nodejs/24.1.0/bin/npx
```

I'm not sure why those differ (or how to change them appropriately) given the shims themselves look almost identical (other than npm vs npx as command) as do the links in the install /bin directory:

```
> ls -la ~/.asdf/installs/nodejs/24.1.0/bin
drwxr-xr-x 2 aaron aaron      4096 Jun 11 12:14 .
drwxr-xr-x 6 aaron aaron      4096 Jun  5 15:52 ..
lrwxrwxrwx 1 aaron aaron        45 Jun  5 15:52 corepack -> ../lib/node_modules/corepack/dist/corepack.js
lrwxrwxrwx 1 aaron aaron        40 Jun  5 16:21 latest -> ../lib/node_modules/latest/bin/latest.js
-rwxr-xr-x 1 aaron aaron 127238104 Jun  5 15:52 node
lrwxrwxrwx 1 aaron aaron        38 Jun 11 12:14 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx 1 aaron aaron        38 Jun 11 12:14 npx -> ../lib/node_modules/npm/bin/npx-cli.js
```

**Comment by Marzdor** [comment] 2025-10-16 21:46
I am seeing a similar issue I think. The node version is the version I want to use for the project I'm working on.
When I do `npm i` I get a warning about npm version.

```
npm warn EBADENGINE   required: { node: '20.19.0', npm: '11.2.0' },
npm warn EBADENGINE   current: { node: 'v20.19.0', npm: '10.8.2' }
```

```
$ node -v
v20.19.0
$ npm -v
10.8.2
$ asdf info
OS:
Linux void 6.12.52-1-lts #1 SMP PREEMPT_DYNAMIC Sun, 12 Oct 2025 19:28:28 +0000 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.3.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2025 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

BASH VERSION:
5.3.3(1)-release

ASDF VERSION:
v0.18.0 (revision 2114f1e)

ASDF INTERNAL VARIABLES:
ASDF_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/home/m/.asdf
ASDF_CONFIG_FILE=/home/m/.asdfrc

ASDF INSTALLED PLUGINS:
nodejs    https://github.com/asdf-vm/asdf-nodejs.git
          90b8ecaa556916daba983a7b01869a9ea682f285
```
