### ISSUE TITLE
bug: cannot create directory ‘/opt/asdf-vm/tmp’: Permission denied

### ISSUE THREAD

**Issue by wandyirawan** [asdf-vm/asdf-nodejs#277] opened 2021-12-22 22:48 UTC
### Describe the Bug

when i try install nodejs, show error mkdir: cannot create directory ‘/opt/asdf-vm/tmp’: Permission denied

### Steps to Reproduce

asdf list all nodejs 14

### Expected Behaviour

show all list nodejs

### Actual Behaviour

mkdir: cannot create directory ‘/opt/asdf-vm/tmp’: Permission denied

### Environment

```shell
OS:
Linux pahvo 5.10.84-1-MANJARO asdf-vm/asdf#1 SMP PREEMPT Wed Dec 8 09:50:30 UTC 2021 x86_64 GNU/Linux

SHELL:
zsh 5.8 (x86_64-pc-linux-gnu)

ASDF VERSION:
v0.8.1

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/asdf-vm

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
```

### asdf plugins affected (if relevant)

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git

**Comment by Stratus3D** [comment] 2021-12-23 14:36
@wandyirawan I think this issue is specific to the nodejs plugin so I have transferred it to the asdf-nodejs repo issue tracker.

@augustobmoura this bug doesn't look familiar to me, so I was wondering if you thought this might have anything to do with the recent PRs.

**Comment by dsakuma** [comment] 2021-12-23 20:45
I'm having the same problem. Also using Manjaro Linux.

My  `~/.tool-versions':
`nodejs 14.18.0`

When running 'asdf install'

The following message is displayed:
`mkdir: cannot create directory ‘/opt/asdf-vm/tmp’: Permission denied`

**Comment by gkapfham** [comment] 2021-12-24 01:14
I am writing to confirm that I am experiencing the same error on Arch Linux. Here are details about my operating system:

```
Linux  5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux
```

Here is the version of `asdf` that I am currently running:

```
v0.8.1
```

I typed the following command that I found from the README file:

```
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
```

If I type the command `asdf list all nodejs` I see the following error in my terminal window:

```
mkdir: cannot create directory ‘/opt/asdf-vm/tmp’: Permission denied
```

Thanks for your work on this plugin for asdf! If you have any feedback on how to resolve this issue, it would be greatly appreciated!

**Comment by augustobmoura** [comment] 2021-12-24 03:08
Hmm, I think I know what is going on. It was actually a "bugfix" that actually made this current bug surface. If you look on commit https://github.com/asdf-vm/asdf-nodejs/commit/800e244e784999fd80c66d72babf4bcc8112a5b3, on file `lib/utils.sh` existed a typo, we were fallbacking `ASDF_DATA_DIR` to `ASDF_HOME`, the problem is that `ASDF_HOME doesn't exist anywhere, the correct name for the variable is `ASDF_DIR`, so the current bug was not reached in the past:

```.diff
+ export ASDF_NODEJS_CACHE_DIR="${ASDF_DATA_DIR:-${ASDF_DIR:-$HOME/.asdf}}/tmp/$ASDF_NODEJS_PLUGIN_NAME/cache"

# ...

- versions_cache_dir="${ASDF_DATA_DIR:-${ASDF_HOME:-$HOME/.asdf}}/tmp/$(plugin_name)/cache"
+ versions_cache_dir="$ASDF_NODEJS_CACHE_DIR/versions-tab"
```

The problem is that we should never use `ASDF_DIR` in this case. [`asdf-core` doesn't use `ASDF_DIR`](https://github.com/asdf-vm/asdf/blob/ac1a35b85bde049b9e2d531032eb55534e38ffe7/lib/utils.bash#L40-L48) when resolving the directory for installing new plugins/versions, neither should we use it for our cache.

I will open a new PR fixing this, and some other issues that will probably arise from this discrepancy between our logic and `asdf-core`

**Comment by aptinio** [comment] 2021-12-24 03:35
From what I understand from http://asdf-vm.com/manage/configuration.html#environment-variables, `ASDF_NODEJS_CACHE_DIR` should be inside `ASDF_DATA_DIR`, falling back directly to `~/.asdf` if `ASDF_DATA_DIR` is not set, something like:

```sh
export ASDF_NODEJS_CACHE_DIR="${ASDF_DATA_DIR:-$HOME/.asdf}/tmp/$ASDF_NODEJS_PLUGIN_NAME/cache"

**Comment by augustobmoura** [comment] 2021-12-24 03:38
> From what I understand from http://asdf-vm.com/manage/configuration.html#environment-variables, `ASDF_NODEJS_CACHE_DIR` should be inside `ASDF_DATA_DIR`, falling back directly to `~/.asdf` if `ASDF_DATA_DIR` is not set, something like:
> 
> ```shell
> export ASDF_NODEJS_CACHE_DIR="${ASDF_DATA_DIR:-$HOME/.asdf}/tmp/$ASDF_NODEJS_PLUGIN_NAME/cache"
> ```

Yes, that is right, it should not fallback to ASDF_DIR at all

**Comment by augustobmoura** [comment] 2021-12-24 03:45
Check if that solves the issue. If it doesn't, we reopen the issue

**Closed** 2021-12-24 03:45 UTC

**Comment by aptinio** [comment] 2021-12-24 03:50
That fixed it for me. Thank you @augustobmoura <3

**Comment by gkapfham** [comment] 2021-12-24 22:25
Hello @augustobmoura, thanks for your efforts in fixing this defect. I am writing to confirm that  this fix works for me and I am now able to use `asdf` to install NodeJS. I have tried multiple commands and they all seem to work correctly now! Thanks!
